version: 1.2
workflows:
   - name: demo-fastqc-wf
     subclass: nfl
     primaryDescriptorPath: /nextflow.config
     testParameterFiles:
          -  /demo-fastqc-wf/tests/test-job-1.json
     filters:
         branches:
             - main
